### ISSUE TITLE
feat: Optimize configuration items, add etcd.prefix and schema

### ISSUE THREAD

**Issue by dickens7** [apache/apisix-helm-chart#111]
Optimize configuration items, add etcd.prefix and schema

**Comment by tokers** [comment]
@dickens7 You mean this? https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/values.yaml#L202

**Comment by dickens7** [comment]
> @dickens7 You mean this? https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/values.yaml#L202

yes

**Comment by tokers** [comment]
Then we have supported it.

**Comment by dickens7** [comment]
> @dickens7 You mean this? https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/values.yaml#L202

I'm sorry that the understanding is wrong here, it should be the etcd.prefix configuration of the corresponding apisix-dashboard here.

https://github.com/apache/apisix-dashboard/blob/master/api/conf/conf.yaml#L48

This PR is for apisix-dashboard.

**Comment by dickens7** [comment]
obsolete
