### ISSUE TITLE
mkdir: cannot create directory '/bitnami/etcd': Permission denied

### ISSUE THREAD

**Issue by lijingrs** [apache/apisix-helm-chart#117]
mkdir: cannot create directory '/bitnami/etcd': Permission denied

is this ok? 

![image](https://user-images.githubusercontent.com/20733031/126810598-e8e6f3ea-4bf1-46a0-8536-2189e150bba3.png)

**Comment by tokers** [comment]
@JackLiMEM Which directory were used in the host as the binding of this one in the container.

**Comment by JackLiMEM** [comment]
> @JackLiMEM Which directory were used in the host as the binding of this one in the container.

 "containerdRootDir": "/var/lib/rancher/k3s/agent/containerd",
    "containerdEndpoint": "/run/k3s/containerd/containerd.sock",
    "rootDir": "/var/lib/rancher/k3s/agent/containerd/io.containerd.grpc.v1.cri",
    "stateDir": "/run/k3s/containerd/io.containerd.grpc.v1.cri"

**Comment by tao12345666333** [comment]
please see https://github.com/apache/apisix-helm-chart/issues/105#issuecomment-864757267

**Comment by jerry3k** [comment]
did you try chmod 777 on the host dir ?

**Comment by JackLiMEM** [comment]
> please see [#105 (comment)](https://github.com/apache/apisix-helm-chart/issues/105#issuecomment-864757267)

Thanks,It seems that it was caused by the k8s version upgrade and this can really solve this problem
