### ISSUE TITLE
the pod is pending, just follow the official website steps

### ISSUE THREAD

**Issue by tutuV** [apache/apisix-helm-chart#119]
只是按照官网步骤，继续安装，没有正常运行 。
Just follow the official website steps, continue to install, did not work properly.

是不是需要自己创建pv，供etcd使用？
Do I need to create PV for etcd use?

![image](https://user-images.githubusercontent.com/49155687/127098820-6eeaf5ba-957c-42cb-b3ba-a2629b054e66.png)

![image](https://user-images.githubusercontent.com/49155687/127098850-6a8c1b67-be25-4949-8992-f6a5e62a4a46.png)

kubectl describe pod apisix-etcd-1 -n gw-apisix
![image](https://user-images.githubusercontent.com/49155687/127099013-ad8f2d62-aab4-4817-aea7-2a3595ce9aff.png)

![image](https://user-images.githubusercontent.com/49155687/127099096-1ccafdd2-922f-469e-b6c3-bfda04767665.png)

**Comment by tokers** [comment]
@tutuV Some contexts we required to troubleshoot this issue.

1. What's your Kubernetes version?
2. 2. What's your Kubernetes distro?

**Comment by tao12345666333** [comment]
This problem should be related to the configuration of your cluster. 
You can check https://github.com/bitnami/charts/tree/master/bitnami/etcd project and modify the persistence configuration

https://github.com/bitnami/charts/tree/master/bitnami/etcd#persistence-parameters


```
helm install apisix charts/apisix --set gateway.type=NodePort --set ingress-controller.enabled=true --namespace ingress-apisix
```

**Comment by tutuV** [comment]
> 1. 你的 Kubernetes 发行版是什么？

**Comment by tutuV** [comment]
> @tutuV Some contexts we required to troubleshoot this issue.
> 
> 1. What's your Kubernetes version? 
> 2. 1. What's your Kubernetes distro?

1.21.0  安装在本地环境

**Comment by tutuV** [comment]
> @tutuV Some contexts we required to troubleshoot this issue.
> 
> 1. What's your Kubernetes version?
> 2. 1. What's your Kubernetes distro?

1.21.0    安装在本地环境中。下面是kubeadm-config.yaml文件的内容
![image](https://user-images.githubusercontent.com/49155687/127251228-ac57ddb3-175c-48d3-858e-2d64f24337e7.png)

**Comment by tutuV** [comment]
@tokers 
1.21.0 安装在本地环境中。下面是kubeadm-config.yaml文件的内容
![image](https://user-images.githubusercontent.com/49155687/127251572-ca83277e-84a9-4850-a02c-d3c7a124386c.png)

**Comment by tutuV** [comment]
@tokers 1.21.0  本地安装的。下面是kubeadm-config.yaml内容：
![image](https://user-images.githubusercontent.com/49155687/127251727-e3a91d2c-547f-47d2-ab16-983af9e2209a.png)

**Comment by tutuV** [comment]
@tao12345666333 你的意思是，下载 apisix-helm-chart包，解压 apisix-helm-chart/charts/apisix/etcd-6.2.6.tgz ，修改相关配置，再次helm  package  etcd 。上述操作完成后，再安装apisix ?
问题是，修改那些配置呢 ？   
------------------------------------------------
What you mean is, download the apisix-helm-chart package, decompress the apisix-helm-chart/charts/apisix/etcd-6.2.6.tgz, modify the relevant configuration, and ' helm package etcd' again. After the preceding operations are complete, install apisix?
The question is, which configurations to modify?

**Comment by tao12345666333** [comment]
https://github.com/bitnami/charts/tree/master/bitnami/etcd#persistence-parameters

You can change the `persistence.storageClass` to your storageClass. And you need to ensure that you have an available storageClass resource https://kubernetes.io/docs/concepts/storage/storage-classes/

**Comment by tutuV** [comment]
@tao12345666333  helm install apisix apisix/apisix  \
    --set admin.allow.ipList="" \
    --set etcd.volumePermissions.enabled=true \
    --namespace ingress-apisix

静态绑定pv卷，再执行上述命令可以成功。注意，accessModes： ReadWriteOnce 
你说的那种方式没尝试。
吐槽下官网文档。不用自己创建pv 也可以 的说法 是错误的。
你为什么把这个标记成 question ？！这对照官网文档来说 ，就是个问题 ！！！
--------------
The PV volume can be statically bound and the preceding command can be executed successfully.Note accessModes: ReadWriteOnce
The way you said it wasn't tried.
Make fun of the official website document.It would be wrong to say that you don't have to create your own PV.
Why do you mark this as a question?!This is a problem compared to the official website documentation!!

**Comment by tao12345666333** [comment]
feel free to reopen it, if you think it's a problem

**Comment by tao12345666333** [comment]
This document will only cover how to deploy apisix. Note that etcd is one of our dependencies, we use the bitnami/etcd chart.

If you don't want to use bitnami/etcd chart, or you are not familiar with Kubernetes, you can also follow this article https://github.com/apache/apisix-ingress-controller/blob/master/docs/en/latest/practices /the-hard-way.md#etcd-installation

**Comment by tutuV** [comment]
@tao12345666333 非常谢谢。稍后我再了解一下。其实你可以讲中文，国际化 不一定非得是英文。

**Comment by tutuV** [comment]
已经解决。官网文档太乱，自己消化理解后，就可以了。

**Comment by endersonmenezes** [comment]
This issue help me, thx! :)

**Comment by tao12345666333** [comment]
@endersonmenezes I'm glad to help you, do you encounter any other problems in use？
