### ISSUE TITLE
CI: host helm charts on GitHub pages.

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-helm-chart#120]
Currently our publishing process is not fully automated, and the content in https://charts.apiseven.com and GitHub are not synchronized in real time, which is not conducive to the open source collaboration of this project.

I think we can host helm charts on GitHub pages. I have tested successfully in my fork repo.

```
➜  ~ helm repo add x-apisix https://moelove.info/apisix-helm-chart/
"x-apisix" has been added to your repositories
➜  ~ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "demo" chart repository
...Successfully got an update from the "apisix" chart repository
...Successfully got an update from the "ingress-nginx" chart repository
...Successfully got an update from the "x-apisix" chart repository
Update Complete. ⎈Happy Helming!⎈
➜  ~ helm search repo x-apisix
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION                                    
x-apisix/apisix                         0.3.6           2.7.0           A Helm chart for Apache APISIX                 
x-apisix/apisix-dashboard               0.1.6           2.7.0           A Helm chart for Apache APISIX Dashboard       
x-apisix/apisix-ingress-controller      0.5.1           1.0.0           Apache APISIX Ingress Controller for Kubernetes

```

We need to solve a few problems to apply these changes to this project:

- [x] create a `gh-pages` branch for host charts
- [ ] redirect `https://charts.apiseven.com` to `https://apache.github.io/apisix-helm-chart` to avoid breaking users

**Comment by tokers** [comment]
That'd be better for the maintainment. cc @juzhiyuan We need your kindly help with step 2 .

**Comment by juzhiyuan** [comment]
@tokers What should I do in the DNS portal? Just set 3xx to `https://apache.github.io/apisix-helm-chart`?
