### ISSUE TITLE
external ip issue when change from Nodeport to LB ingress in value file

### ISSUE THREAD

**Issue by yangtian9999** [apache/apisix-helm-chart#130]
Hi,

When I change to use ingress for gateway in the helm value file, the service could not get external IP for the ingress.

gateway:
  #type: NodePort
  # If you want to keep the client source IP, you can set this to Local.
  # ref: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: nlb
  http:
    enabled: true
    servicePort: 80
    containerPort: 9080
  tls:
    enabled: false
    servicePort: 443
    containerPort: 9443
    http2:
      enabled: true
  stream:  # L4 proxy (TCP/UDP)
    enabled: false
    tcp: []
    udp: []
  ingress:
    enabled: true
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: apisix.local
        paths: []
    tls: []
  #  - secretName: apisix-tls
  #    hosts:
  #      - chart-example.local

**Comment by tokers** [comment]
Please provide more details about your apisix ingress controller and kubernetes versions.

**Comment by yangtian9999** [comment]
1.19.8 installed by rke.

At very first, I used default helm value to install apisix. Then I used rancher to setup ingress for service with port 9080.

Apisix dashboard was bind to ingress successfully.

But gateway 9080 failed.

**Comment by tokers** [comment]
The ingress class in your resource is `nginx` and it won't be watched by apisix ingress controller.

**Comment by tokers** [comment]
Just try to change it to `apisix` and see what happens.

**Comment by yangtian9999** [comment]
The following yaml was generated by rancher default ingress.  You mean that I can not use rancher default nginx-ingress? 
I tried just moment ago, I used default helm values to install apisix, and then use rancher default ingress to setup, still can not use the host normally. 

Thanks.

development environment:  k3s+1.20.8, rancher 2.5.7



apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: user-nmbdh
    field.cattle.io/ingressState: '{"YWcvYXBpc2l4L2FnLmRldi15YW5ndGlhbi5zdXRwYy5jb20vLzkwODA=":""}'
    field.cattle.io/publicEndpoints: '[{"addresses":["10.10.xxx.xxx"],"port":80,"protocol":"HTTP","serviceName":"apisix:apisix-gateway","ingressName":"apisix:ag","hostname":"apigateway.xxx.com","allNodes":false}]'
  creationTimestamp: "2021-08-18T02:06:05Z"
  generation: 1
  labels:
    cattle.io/creator: norman
  managedFields:
  - apiVersion: extensions/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/creatorId: {}
          f:field.cattle.io/ingressState: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
      f:spec:
        f:rules: {}
    manager: Go-http-client
    operation: Update
    time: "2021-08-18T02:06:05Z"
  - apiVersion: extensions/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:field.cattle.io/publicEndpoints: {}
    manager: rancher
    operation: Update
    time: "2021-08-18T02:06:05Z"
  - apiVersion: extensions/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: traefik
    operation: Update
    time: "2021-08-18T02:06:05Z"
  name: ag
  namespace: apisix
  resourceVersion: "42452199"
  uid: f686ec7a-f55f-4021-bb0b-076264e135a4
spec:
  rules:
  - host: apigateway.xxx.com
    http:
      paths:
      - backend:
          serviceName: apisix-gateway
          servicePort: 9080
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: 10.10.xxx.xxx

**Comment by yangtian9999** [comment]
sorry, @tokers ,  i will use your comments to update values and try again. 

Thanks for your help.

**Comment by yangtian9999** [comment]
Hi, @tokers 

helm install got error message: 
Error: Ingress.extensions "apisix" is invalid: spec.rules[0].http.paths[0].path: Invalid value: "map[backend:map[service:map[serviceName:apisix-gateway servicePort:80]] path:/ pathType:Prefix]": must be an absolute path

I tried many times by  this:

gateway:
  type: NodePort
  # If you want to keep the client source IP, you can set this to Local.
  # ref: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  externalTrafficPolicy: Cluster
  # type: LoadBalancer
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: nlb
  http:
    enabled: true
    servicePort: 80
    containerPort: 9080
  tls:
    enabled: false
    servicePort: 443
    containerPort: 9443
    http2:
      enabled: true
  stream:  # L4 proxy (TCP/UDP)
    enabled: false
    tcp: []
    udp: []
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: "ag.xx.xx.xx"
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                serviceName: apisix-gateway
                servicePort: 80
    tls: []

**Comment by tokers** [comment]
> The following yaml was generated by rancher default ingress. You mean that I can not use rancher default nginx-ingress?
> I tried just moment ago, I used default helm values to install apisix, and then use rancher default ingress to setup, still can not use the host normally.
> 
> Thanks.
> 
> development environment: k3s+1.20.8, rancher 2.5.7
> 
> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
> annotations:
> field.cattle.io/creatorId: user-nmbdh
> field.cattle.io/ingressState: '{"YWcvYXBpc2l4L2FnLmRldi15YW5ndGlhbi5zdXRwYy5jb20vLzkwODA=":""}'
> field.cattle.io/publicEndpoints: '[{"addresses":["10.10.xxx.xxx"],"port":80,"protocol":"HTTP","serviceName":"apisix:apisix-gateway","ingressName":"apisix:ag","hostname":"apigateway.xxx.com","allNodes":false}]'
> creationTimestamp: "2021-08-18T02:06:05Z"
> generation: 1
> labels:
> cattle.io/creator: norman
> managedFields:
> 
> * apiVersion: extensions/v1beta1
>   fieldsType: FieldsV1
>   fieldsV1:
>   f:metadata:
>   f:annotations:
>   .: {}
>   f:field.cattle.io/creatorId: {}
>   f:field.cattle.io/ingressState: {}
>   f:labels:
>   .: {}
>   f:cattle.io/creator: {}
>   f:spec:
>   f:rules: {}
>   manager: Go-http-client
>   operation: Update
>   time: "2021-08-18T02:06:05Z"
> * apiVersion: extensions/v1beta1
>   fieldsType: FieldsV1
>   fieldsV1:
>   f:metadata:
>   f:annotations:
>   f:field.cattle.io/publicEndpoints: {}
>   manager: rancher
>   operation: Update
>   time: "2021-08-18T02:06:05Z"
> * apiVersion: extensions/v1beta1
>   fieldsType: FieldsV1
>   fieldsV1:
>   f:status:
>   f:loadBalancer:
>   f:ingress: {}
>   manager: traefik
>   operation: Update
>   time: "2021-08-18T02:06:05Z"
>   name: ag
>   namespace: apisix
>   resourceVersion: "42452199"
>   uid: f686ec7a-f55f-4021-bb0b-076264e135a4
>   spec:
>   rules:
> * host: apigateway.xxx.com
>   http:
>   paths:
>   
>   * backend:
>     serviceName: apisix-gateway
>     servicePort: 9080
>     pathType: ImplementationSpecific
>     status:
>     loadBalancer:
>     ingress:
>   * ip: 10.10.xxx.xxx

The default ingress controller is ingress-nginx in rancher, and ingress resources with `kubernetes.io/ingress.class: nginx
` won't be processed by apisix ingress controller.

**Comment by yangtian9999** [comment]
problem fixed.

use default value and helm command to install.

Then, use apisix-gateway http service 80 port and nginx-ingress to setup the hostname in rancher.

Finally, we can use rancher default nginx-ingress host name for apisix-gateway which was deployed within the same k8s
