### ISSUE TITLE
error when install apisix with helm3.6.3

### ISSUE THREAD

**Issue by a95241815** [apache/apisix-helm-chart#131]
I install apisix as follow:
```
helm install apisix apisix/apisix
```
an error occur like "CustomResourceDefinition is deprecated"

**Comment by tokers** [comment]
> I install apisix as follow:
> 
> ```
> 
> helm install apisix apisix/apisix
> 
> ```
> 
> an error occur like "CustomResourceDefinition is deprecated"
> 
> 
> 
> 

Is it related to the version of CRD? Don't worry about it, it's now harmless and we are about to use the v1 version of CRD in the future.

**Comment by a95241815** [comment]
thank u
