### ISSUE TITLE
Bug: could not change the user password by configmap

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix-helm-chart#140]
come from user report in wechat group `APache APISIX 交流群`
wechat ID：Alec

APISIX docer image: apache/apisix:2.7-alpine
APISIX dashboard image：apache/apisix-dashboard:2.7
build on k8s

config map:
![configmap](https://user-images.githubusercontent.com/2561857/131820291-32b613f7-d75e-4709-ad5e-018fa40672c7.png)

部署后的cm文件：
![cmfile](https://user-images.githubusercontent.com/2561857/131820431-1ea6099f-2837-4fe6-9ecc-cf0c5f55d8cb.png)

update user password, but the modification does not take effect, can only login with default password.

**Comment by tokers** [comment]
Since we don't mount the whole directory with the `ConfigMap`, users changed the `ConfigMap` resource manually have to restart the apisix-dashboard workload.

You may just use `kubectl rollout restart deployment {name of apisix-dashboard deployment}` to let it restart.

**Comment by wjmmjr** [comment]
The problem has been solved：delete the pod and restart it

**Comment by liuxiran** [comment]
Thanks for your feedback @wjmmjr , next time you can try the command line.
