### ISSUE TITLE
No joy on docker desktop or Digital Ocean k8s

### ISSUE THREAD

**Issue by 8thblock** [apache/apisix-helm-chart#153]
Evaluating APISIX to replace our NGINX ingress and it does not seem to work on Kubernetes cluster that comes as a default with Docker Desktop

Here are the details:
OS: mac OS
Env: k8s that comes with docker desktop
Installed by: 
```
cd /path/to/apisix-helm-chart
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
kubectl create ns ingress-apisix
helm install apisix charts/apisix \
  --set gateway.type=NodePort \
  --set ingress-controller.enabled=true \
  --namespace ingress-apisix
kubectl get service --namespace ingress-apisix
```
Chart used:
```
remote url: https://github.com/apache/apisix-helm-chart.git
branch: master
```

Everything installed ok:
```
NAME                                            READY   STATUS    RESTARTS   AGE
pod/apisix-56c976fc-jrf6l                       1/1     Running   0          49m
pod/apisix-etcd-0                               1/1     Running   0          49m
pod/apisix-etcd-1                               1/1     Running   0          49m
pod/apisix-etcd-2                               1/1     Running   0          49m
pod/apisix-ingress-controller-b5f5d49db-6fp7n   1/1     Running   0          49m
pod/httpbin                                     1/1     Running   0          33m

NAME                                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/apisix-admin                ClusterIP   10.104.186.82   <none>        9180/TCP            49m
service/apisix-etcd                 ClusterIP   10.101.172.59   <none>        2379/TCP,2380/TCP   49m
service/apisix-etcd-headless        ClusterIP   None            <none>        2379/TCP,2380/TCP   49m
service/apisix-gateway              NodePort    10.106.23.81    <none>        80:31205/TCP        49m
service/apisix-ingress-controller   ClusterIP   10.110.119.97   <none>        80/TCP              49m
service/httpbin                     ClusterIP   10.96.245.203   <none>        80/TCP              33m

NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/apisix                      1/1     1            1           49m
deployment.apps/apisix-ingress-controller   1/1     1            1           49m

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/apisix-56c976fc                       1         1         1       49m
replicaset.apps/apisix-ingress-controller-b5f5d49db   1         1         1       49m

NAME                           READY   AGE
statefulset.apps/apisix-etcd   3/3     49m
```

However: No  routes are registering if I try and upon close inspection I noticed there are plenty of errors in the ingress controller. See attached logs. Is there anything that I am missing? Just followed your docs and got the latest helm
[errors.log](https://github.com/apache/apisix-helm-chart/files/7315851/errors.log)

**Comment by 8thblock** [comment]
Alas exact same issue in the k8s cluster on Digital Ocean ...

**Comment by tao12345666333** [comment]
Can you please run `kubectl get ar -A` ?

**Comment by tao12345666333** [comment]
And what's your k8s version? For kubernetes v1.22+ it using CRD v1 apiversion. We have completed the adaptation and will release it in the v1.3 version of apisix-ingress. This version will be released next week.

**Comment by 8thblock** [comment]
Server Version: v1.19.7

**Comment by 8thblock** [comment]
Let me reinstall and give you a list of routes

**Comment by tokers** [comment]
@8thblock If you want to use online helm repo to install Apache APISIX & the Ingress Controller, you should use the correct repo address, i.e. https://charts.apiseven.com.

As for the running issue, I checked out the error.log and there are some logs just like:

```
2021-10-09T21:59:51+08:00	[31merror[0m	apisix/route.go:117	failed to list routes: Get http://apisix-admin:9180/apisix/admin/routes: dial tcp 10.104.186.82:9180: connect: connection refused
```

Could you try to access the `apisix-admin:9180` manually, and paste the result here?

**Comment by tao12345666333** [comment]
can you try to delete apisix-ingress pod?

**Comment by 8thblock** [comment]
Seems to have solved the issue. Let me quickly try the router

**Comment by 8thblock** [comment]
Can confirm it is all working now! Thank you for your help

**Comment by tao12345666333** [comment]
Next week apisix-ingress v1.3 will be released, and the Helm chart will be updated at that time.
Thanks for your quick confirmation.
