### ISSUE TITLE
error.log 日志输出

### ISSUE THREAD

**Issue by siaron** [apache/apisix-helm-chart#159]
- 部署到k8s后日志插件输出的日志在error.log中怎么看不到
```
/usr/local/apisix/logs # ls -l
total 4
lrwxrwxrwx    1 root     root            11 Oct  2 01:54 access.log -> /dev/stdout
lrwxrwxrwx    1 root     root            11 Oct  2 01:54 error.log -> /dev/stderr
-rw-r--r--    1 root     root             2 Oct 20 07:46 nginx.pid
```
- 这个error.log 为什么也打印重定向到了` /dev/stderr`
- k8s 下怎么看到这个日志输出

**Comment by tokers** [comment]
> * 部署到k8s后日志插件输出的日志在error.log中怎么看不到
> 
> ```
> /usr/local/apisix/logs # ls -l
> total 4
> lrwxrwxrwx    1 root     root            11 Oct  2 01:54 access.log -> /dev/stdout
> lrwxrwxrwx    1 root     root            11 Oct  2 01:54 error.log -> /dev/stderr
> -rw-r--r--    1 root     root             2 Oct 20 07:46 nginx.pid
> ```
> 
> * 这个error.log 为什么也打印重定向到了` /dev/stderr`
> * k8s 下怎么看到这个日志输出

1. Make sure the log level is enough to show your logs.
2. The redirection was set up in the docker file.
3. just use `kubectl logs` command.

**Comment by tao12345666333** [comment]
This issue has not been updated for too long, I will close it. If you still have questions, please feel free to reopen it.
