### ISSUE TITLE
Name conflict of dashboard as a subchart

### ISSUE THREAD

**Issue by xiaoFine** [apache/apisix-helm-chart#170]
When I try to install apisix and cover values by '--set' in cmd, I found that there is a conflict about the subchart name of apisix-dashboard. 

In charts/apisix/Chart.lock, it gives 'apisix-dashboard' , so I give the value, for example,  by setting 'apisix-dashboard.fullnameOverride=apisix-dashboard'.

But actually, the debug logs shows the actual name of the subchart is 'dashboard':
```bash
COMPUTED VALUES:
admin:
  ...
apisix:
  ...
autoscaling:
  ...
dashboard:
  fullnameOverride: ""
  ...
``` 

It's quite confusing

**Comment by tao12345666333** [comment]
Chart.lock only represents the name of the corresponding sub chart itself.

Aliasing has been performed in Chart.yaml, 
https://github.com/apache/apisix-helm-chart/blob/cf0f0c529f44c5b2e70ac347d741c788bc1a0ec6/charts/apisix/Chart.yaml#L46-L50

and there is a corresponding configuration location in values.yaml.
https://github.com/apache/apisix-helm-chart/blob/cf0f0c529f44c5b2e70ac347d741c788bc1a0ec6/charts/apisix/values.yaml#L330
