### ISSUE TITLE
docs: Failed to deploy under non ingress-apisix namespace

### ISSUE THREAD

**Issue by jikunchong** [apache/apisix-helm-chart#176]
### Issue description
在非 ingress-apisix 命名空间下部署时， 报错：
nc: bad address 'apisix-admin.ingress-apisix.svc.cluster.local'
 waiting for apisix-admin

原因：
wait-apisix-admin 初始化脚本，只找固定命名空间：ingress-apisix
  initContainers:
    - name: wait-apisix-admin
      image: 'busybox:1.28'
      command:
        - sh
        - '-c'
        - >-
          until nc -z apisix-admin.ingress-apisix.svc.cluster.local 9180 ; do
          echo waiting for apisix-admin; sleep 2; done;

手动变更后，才能正常初始化。

### Environment

* your apisix-ingress-controller version (output of `apisix-ingress-controller version --long`);
* your Kubernetes cluster version (output of `kubectl version`);
* if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (`uname -a`).

### Minimal test code / Steps to reproduce the issue

1.
2.
3.

**Comment by jikunchong** [comment]
那针对这种一键部署的，建议在官方文档中多说明一下有关指定自己的命名空间时需要怎么做，谢谢

**Comment by tao12345666333** [comment]
This configuration item is newly added, the document has not been completed yet, welcome to submit a PR

**Comment by jikunchong** [comment]
ok，tks
