### ISSUE TITLE
docs: add READEME.md to artifacthub.io

### ISSUE THREAD

**Issue by zaunist** [apache/apisix-helm-chart#189]
I want to deploy apisix-dashboard with helm, so I visit artifacthub.io to search  `apisix-dashboard`, but get the `apisix-dashboard` doesn't have READEME.md

![image](https://user-images.githubusercontent.com/38528079/144537231-3b61abc3-abcf-4069-8842-777c38739baf.png)

Do we need to add README.md for `apisix-dashboard` ?

**Comment by tao12345666333** [comment]
Welcome to open a PR.
