### ISSUE TITLE
Cannot use apisix.apache.org/v2beta2 on last version

### ISSUE THREAD

**Issue by gardun0** [apache/apisix-helm-chart#217]
Hello,

I'm having this issue with the version `0.7.3`. As far as i know `apisix.apache.org/v2beta2` must be available within this version, but  it's replaced with `apisix.apache.org/v2beta1`  once i create it.

I even changed this value `ingress-controller.config.kubernetes.apisixRouteVersion` on the helm values.

Is this normal?

**Comment by tao12345666333** [comment]
can you run `kubectl api-resources --api-group=apisix.apache.org` ?

**Comment by gardun0** [comment]
> can you run `kubectl api-resources --api-group=apisix.apache.org` ?

Yeah, i think this is an issue from GKE, anyways i encountered that the `authentication` property doesn't set key-auth config properly within this CR version.
