### ISSUE TITLE
Proposal: APISIX can run as DaemonSet

### ISSUE THREAD

**Issue by Gallardot** [apache/apisix-helm-chart#225]
In the microservices architecture, multiple independent business services may use independent registries (Eureka \ Nacos \Consul). We hope that APISIX can be deployed to the cluster as daemonset. Microservices can access the services of other independent businesses by calling APISIX of local nodes.

A picture is worth a thousand words.

![apisix-mesh](https://user-images.githubusercontent.com/329265/151479428-95734d34-b3b7-4ebc-8349-4fada2db1278.jpg)

**Comment by gxthrj** [comment]
It is a good idea, btw I would like to ask if the scenario of this proposal is to use Apache APISIX to handle east-west traffic inside Kubernetes?

**Comment by gxthrj** [comment]
And I would like to ask why not choose to use `deployment` + `HPA` to deploy Apache APISIX, is there any special advantage of using `daemonset`?

**Comment by Gallardot** [comment]
> It is a good idea, btw I would like to ask if the scenario of this proposal is to use Apache APISIX to handle east-west traffic inside Kubernetes?

Yes.



> And I would like to ask why not choose to use `deployment` + `HPA` to deploy Apache APISIX, is there any special advantage of using `daemonset`?

We could use hostnetwork, which would have better performance.

**Comment by gxthrj** [comment]
> We could use hostnetwork, which would have better performance.

We can use `hostnetwork` with `deployment`, too. And set `dnsPolicy` to `ClusterFirstWithHostNet`.

**Comment by tokers** [comment]
@Gallardot Could you provide some real scenarios.

**Comment by gardun0** [comment]
> west

Regarding to this, i don't think this is the purpose of an API Gateway entirely

**Comment by Gallardot** [comment]
#257  has been merged. I will close this one.
