### ISSUE TITLE
Chart apisix-ingress-controller 0.9.0 version was not updated on apisix 0.8.0 dependencies

### ISSUE THREAD

**Issue by gardun0** [apache/apisix-helm-chart#226]
The latest version 0.8.0 of apisix's chart did not upgrade the new version of ingress-controller chart 0.9.0.

**Comment by tokers** [comment]
cc @tao12345666333 Is the ingress-controller chart`0.9.0` matched with apisix `0.8.0`?

**Comment by tao12345666333** [comment]
we need open a PR to upgrade dependencies

**Comment by tokers** [comment]
> 

@gardun0 Would you like to submit a PR to update it?

**Comment by gardun0** [comment]
Sure, Ill Work on it, I've found an issue working this two versions, but I'll try to debug it

**Comment by tao12345666333** [comment]
@gardun0 Do you have time to update this dependency? In the apisix-ingress-controller v0.9.0 chart, we upgraded to APISIX Ingress controller v1.4 which solved a lot of issues. So we need to upgrade this dependency as soon as possible. Currently I have found some issues like https://github.com/apache/apisix-ingress-controller/issues/851
