### ISSUE TITLE
Why not updating etcd version?

### ISSUE THREAD

**Issue by gardun0** [apache/apisix-helm-chart#229]
I've seen this helm charts are using a version from mid 2020, is there a reason for that? If not, why not upgrade it? i believe it'll fix current etcd issues like #197

**Comment by tokers** [comment]
@gardun0 Personally I support to update the default ETCD version. Let's see others' responses.

**Comment by tao12345666333** [comment]
I guess it's just forgotten. 😅

I checked the APISIX code repository and the version of ETCD used in CI is new

**Comment by Gallardot** [comment]
@gardun0 

Agree and welcome to open a PR.

**Comment by gamer22026** [comment]
See https://github.com/etcd-io/etcd/tree/main/CHANGELOG#v35-data-corruption-issue. Probably want to stay on the 3.4 version. The latest Bitnami helm chart for etcd migrated back to 3.4.x version from 3.5.x due to this issue.

**Comment by tokers** [comment]
> See https://github.com/etcd-io/etcd/tree/main/CHANGELOG#v35-data-corruption-issue. Probably want to stay on the 3.4 version. The latest Bitnami helm chart for etcd migrated back to 3.4.x version from 3.5.x due to this issue.

Agree, I think we can use `3.4.18`, APISIX also uses this in the CI.

**Comment by tao12345666333** [comment]
Yes. We can upgrade to 3.4.18
