### ISSUE TITLE
apisix-ingress-controller默认的命名空间，可以改成apisix不？

### ISSUE THREAD

**Issue by xewn** [apache/apisix-helm-chart#236]
默认的命名空间，可以改成apisix不？和另外两个统一一下
helm install apisix-ingress-controller apisix/apisix-ingress-controller --namespace ingress-apisix --create-namespace
每次都因为这个命名空间不统一报错。

**Comment by tao12345666333** [comment]
Sure, welcome to open a PR.

In fact, I recommend deploying with a command like:

```
helm install apisix apisix/apisix --set gateway.type=NodePort --set ingress-controller.enabled=true --set ingress-controller.config.apisix.serviceNamespace=apisix --namespace apisix --create-namespace --set ingress-controller.config.apisix.serviceName=apisix-admin
```

**Comment by xewn** [comment]
你这个命令，好像不会安装apisix dashboard。我是在kubesphere安装的，总是有各种问题，安装不成功。

**Comment by xewn** [comment]
![image](https://user-images.githubusercontent.com/1423410/154268600-5ec47e37-d9c8-4cb5-9c5d-9efd9ca3aa7a.png)

**Comment by tokers** [comment]
@xewn I think the command provided by you is correct, could you provide some details about why the container quit? Such as the log messages.

**Comment by zaunist** [comment]
@xewn I found your apisix is not ready, so dashboard will wait apisix initial success, could you give more info about apisix status ?

**Comment by xewn** [comment]
可以看到日志的。要不你们搞个kubesphere部署一下呢？  我都尝试了很多次了，主要是k8s不懂，自己搞不来。

**Comment by xewn** [comment]
或者我让你们远程来看？

**Comment by tao12345666333** [comment]
I have installed in KubeSphere and everything works fine.

You can try to check your network, or see if there is any valid information in the logs.

**Comment by xewn** [comment]
你是同时安装 apisix  dashboard  ingress？

**Comment by xewn** [comment]
单独安装 apisix dashboard是没问题的。单独安装apisix和ingress也是没问题的。三个一起安装就不行。

**Comment by xewn** [comment]
`helm install apisix apisix/apisix --set gateway.type=NodePort --set ingress-controller.enabled=true --set dashboard.enabled=true --set ingress-controller.config.apisix.serviceNamespace=apisix --namespace apisix --create-namespace --set ingress-controller.config.apisix.serviceName=apisix-admin`
你用这个安装 apisix dashboard ingress，有没问题？

**Comment by tao12345666333** [comment]
here is my install command:

```
elm install apisix apisix/apisix --set gateway.type=NodePort --set ingress-controller.enabled=true --set ingress-controller.config.apisix.serviceNamespace=apisix --namespace apisix --create-namespace --set ingress-controller.config.apisix.serviceName=apisix-admin --set dashboard.enabled=true
```

**Comment by zaunist** [comment]
I have a suggestion, let's change the namespace of the script waiting for apisix to start in the init container in ingress-controller to apisix, and then set the default namespace to apisix consistently. How do you think? @tao12345666333

**Comment by tao12345666333** [comment]
> 
In fact it is configurable.

https://github.com/apache/apisix-helm-chart/blob/2a481404fc85707283df1ce0eda0e6680240d58a/charts/apisix-ingress-controller/templates/deployment.yaml#L54

Of course, I also agree to unify the content in the default document so that users can get started quickly.

**Comment by zaunist** [comment]
> > 
> 
> In fact it is configurable.
> 
> https://github.com/apache/apisix-helm-chart/blob/2a481404fc85707283df1ce0eda0e6680240d58a/charts/apisix-ingress-controller/templates/deployment.yaml#L54
> 
> Of course, I also agree to unify the content in the default document so that users can get started quickly.

I would like to do this work, please assign to me.

**Comment by tao12345666333** [comment]
assigned
