### ISSUE TITLE
apisix upgrade issue, howto upgrade version from old to latest ? 

### ISSUE THREAD

**Issue by andylhz-mojie** [apache/apisix-helm-chart#238]
helm upgrade --install  -n apisix-uat apisix ./apisix
Error: UPGRADE FAILED: cannot patch "apisix-etcd" with kind StatefulSet: StatefulSet.apps "apisix-etcd" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden

**Comment by tokers** [comment]
I think this is because the ETCD statefulset template is changed since the first time you install till now.

**Comment by tokers** [comment]
You may set the `etcd.enabled` to `false`, see https://github.com/apache/apisix-helm-chart/tree/master/charts/apisix#etcd-parameters.

**Comment by andylhz-mojie** [comment]
> > > 
> > 
> > 
> > If I just update the apisix image to latest version and keep the configmap , is that OK ?
> 
> Yeah.

Thanks.
