### ISSUE TITLE
How to configure service discovery with DNS

### ISSUE THREAD

**Issue by tutuV** [apache/apisix-helm-chart#239]
env:  
k8s v1.21.0    
apisix-helm-chart v0.8.2

apisix  values.yaml :
```yaml
discovery:
  enabled: true
  dns:
    servers:
      - "192.168.70.237:8600"
```

consul service.json:
{
    "id": 1,
    "discovery_type": "dns",
    "service_name": "createaccount.service.consul",
    "type": "roundrobin"
}

install command:
kubectl create ns apisix

helm install apisix apisix \
-f apisix/values.yaml \
--set admin.allow.ipList="{0.0.0.0/0}" \
--set admin.type=LoadBalancer \
--set etcd.enabled=true \
--set etcd.persistence.enabled=false \
--set ingress-controller.enabled=true \
--set ingress-controller.config.apisix.serviceNamespace=apisix \
--set dashboard.enabled=true \
--namespace apisix

//192.168.70.22 is apisix-admin lb ip
curl http://192.168.70.22:9180/apisix/admin/upstreams/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d @service.json

error:
kubectl logs -f apisix-xxx -n apisix
 [error] 46#46: *70250 [lua] init.lua:520: http_access_phase(): failed to set upstream: discovery dns is uninitialized,

--------------------------------
i intend to use consul as service registry and apisix's DNS way as service discovery
there are too few documents. i don't know how to configure it correctly .

**Comment by tao12345666333** [comment]
@tutuV  Please check your configuration
xref: https://github.com/apache/apisix/blob/master/docs/en/latest/discovery/dns.md#service-discovery-via-dns

**Comment by tutuV** [comment]
@tao12345666333 it still doesn't work. did anyone tell Apisix that their documentation sucks.

**Comment by tutuV** [comment]
@tao12345666333 it still doesn't work. did anyone tell Apisix that their documentation sucks.
helm-chart-0.8.2/apisix/templates/configmap.yaml
![image](https://user-images.githubusercontent.com/49155687/155259415-e18f2f74-cc5b-44ea-9373-ef7dc1cfb0b8.png)

helm-chart-0.8.2/apisix/values.yaml
![image](https://user-images.githubusercontent.com/49155687/155259518-d7a69f38-d06d-46b6-94ce-3a29714980a2.png)

https://github.com/apache/apisix/blob/master/docs/en/latest/discovery/dns.md#service-discovery-via-dns
![image](https://user-images.githubusercontent.com/49155687/155259576-c72c2671-b3da-4d59-a7d5-3966bece00bb.png)


I can't understand the above three documents correctly. Please briefly tell me how helm-CharT-0.8.2/apisix/values.yaml should be configured to meet my requirements. Or is there a bug here ?

**Comment by tutuV** [comment]
@tao12345666333 I tried a lot, but nothing worked. The documentation is not explicit.

**Comment by tao12345666333** [comment]
You can just using `helm template ` command to see the final generated YAML

**Comment by tutuV** [comment]
i fixed the configuration
