### ISSUE TITLE
Add `lifecycle.postStart` to `apisix` `value.yaml`

### ISSUE THREAD

**Issue by anjia0532** [apache/apisix-helm-chart#247]
k8s docs <https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/>

e.g. <https://github.com/elastic/helm-charts/blob/main/elasticsearch/values.yaml#L275-L293>

**Comment by tokers** [comment]
@anjia0532 It will be better if you can give some real scenarios that people may use it.
