### ISSUE TITLE
feat: kubernetes deployment file configuration files mounted through subPath cannot be dynamically updated

### ISSUE THREAD

**Issue by Hwting** [apache/apisix-helm-chart#253]
### Description

apisix-helm-chart deployment is currently mounted via subPath。Expect dynamic updates by modifying configuration files without restarting pods。e.g. via the Kubernetes API
[A container using a ConfigMap as a subPath volume will not receive ConfigMap updates.](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically)

**Comment by tao12345666333** [comment]
Duplicate with #243 , I will close this issue

xref: https://github.com/apache/apisix-helm-chart/issues/243#issuecomment-1057554086
