### ISSUE TITLE
Request for new apisix-dashboard chart release

### ISSUE THREAD

**Issue by m33li5** [apache/apisix-helm-chart#267]
Seems `apisix-dashboard` is lagging behind in terms of relases.

For example, I made a PR which was merged to master (#264). This PR added support for newer k8s ingress API versions to both `apisix` and `apisix-dashboard` Helm charts.

New version of `apisix` Helm chart was [released](https://github.com/apache/apisix-helm-chart/releases/tag/apisix-0.9.1) which included the PR, but no release for `apisix-dashboard` so dashboard still uses old ingress API.

Can you do a new release for `apisix-dashboard` and then also bump the version in `apisix` Chart dependencies and do a new release of `apisix` aswell?

**Comment by tao12345666333** [comment]
Sure! Are you interested in submitting a PR for release?

**Comment by m33li5** [comment]
> Sure! Are you interested in submitting a PR for release?

Yes, but I'm not sure I know how to make a PR for release. Is it just bumping the chart versions and/or image tags?

**Comment by tao12345666333** [comment]
> > Sure! Are you interested in submitting a PR for release?
> 
> 
> 
> Yes, but I'm not sure I know how to make a PR for release. Is it just bumping the chart versions and/or image tags?

Yes! This time only the content related to Chart has been changed, so you can directly modify the Chart version

**Comment by Senorsen** [comment]
I just wondor why you need / encourage a PR to bump some versions and publish a new release. 😮 

P.S. No offence, I'm curious about this because I think this kind of work often belongs to maintainer's job.

**Comment by tao12345666333** [comment]
I don't think it matters. When a feature we need isn't released, everyone can push it forward, that's the beauty of open source projects

**Comment by tao12345666333** [comment]
New version has been released. I think we can close this one.
