### ISSUE TITLE
APISIX Ingress controller chart need add `metadata.namespace` configuration

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-helm-chart#273]
https://github.com/apache/apisix-helm-chart/blob/d220199e60ad10eb2998e6e57e45fe43df25a44a/charts/apisix-ingress-controller/templates/deployment.yaml#L19-L22

**Comment by jwrookie** [comment]
Can assign to me ?

**Comment by tokers** [comment]
@jwrookie Assigned to you.

**Comment by jwrookie** [comment]
GET

**Comment by tao12345666333** [comment]
#274 has been merged. I will close this one.
Thank you.
