### ISSUE TITLE
break change with affinity?

### ISSUE THREAD

**Issue by Junnplus** [apache/apisix-helm-chart#28]
break change with affinity?

_Originally posted by @Junnplus in https://github.com/apache/apisix-helm-chart/pull/20#discussion_r564489195_

**Comment by tokers** [comment]
I saw the #20, It seems the affinity configuration is incomplete now. We need the affinity capability.

**Comment by tokers** [comment]
@gxthrj

**Comment by tokers** [comment]
> I saw the #20, It seems the affinity configuration is incomplete now. We need the affinity capability.

Also, the bug you mentioned should be fixed. PR's are welcome!
