### ISSUE TITLE
Add configurable initContainer image and tag

### ISSUE THREAD

**Issue by mkocsis-tg** [apache/apisix-helm-chart#294]
Add support for overriding the image and the tag of the initContainers sections in the:
- charts/apisix/templates/daemonset.yaml
- charts/apisix/templates/deployment.yaml

This is required to deploy the chart in an air-gapped K8s cluster, where internet connection is forbidden or limited.

Change it FROM:
```
initContainers:
  - name: wait-etcd
    image: busybox:1.28


```
TO similar what is in the charts/apisix-ingress-controller/templates/deployment.yml
```
initContainers:
  - name: wait-apisix-admin
    image: {{ .Values.initContainer.image }}:{{ .Values.initContainer.tag }}
```

**Comment by tao12345666333** [comment]
I think this is valuable, if you are interested please submit a PR

**Comment by mkocsis-tg** [comment]
Yes, the PR is on the way :)

**Comment by tao12345666333** [comment]
@mkocsis-tg  #295 has been merged. 
I will close this one. Thanks!

**Comment by tao12345666333** [comment]
@mkocsis-tg If you have time please submit a PR to add documentation about this change https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/README.md  :heart:

**Comment by Zeeeeta** [comment]
Sorry I am not familiar with helm and learning, is it possible to also add configurable resources.limits and resources.requests in the values.yaml for the wait-etcd initContainer?
My company's Rancher requires such for every container and I have to manually update those values after installing the chart now.
Thanks.
