### ISSUE TITLE
Etcd cluster with tls

### ISSUE THREAD

**Issue by hyt05** [apache/apisix-helm-chart#3]
etcd version：3.4.3
How can I configure an etcd cluster with tls, I know my certification path clearly。

**Comment by spacewander** [comment]
Do you mean configuring a client certificate for APISIX?

**Comment by hyt05** [comment]
@spacewander  No, I want to connect etcd cluster with tls for apisix, how to set

**Comment by hyt05** [comment]
@spacewander     No, I want apisix to connect to the etcd cluster of tls, how to set it up

**Comment by spacewander** [comment]
> 
> 
> etcd version：3.4.3
> How can I configure an etcd cluster with tls, I know my certification path clearly。

Why you need a certification when you just want to connect a HTTPS server?

**Comment by spacewander** [comment]
Err... Do you mean you want to set a server side certification for etcd? It would be better to ask this question to the community of etcd. It isn't related to APISIX.
