### ISSUE TITLE
apisix-etcd-0 pod start error when use custom cluster domain on k3s

### ISSUE THREAD

**Issue by ncepuwanghui** [apache/apisix-helm-chart#33]
The apisix-etcd-0 pod failed to start when installing apisix-helm-chart on a k3s cluster deployed with a custom domain name.

apisix install command as follows:
```
helm install apisix ./charts/apisix --namespace ingress-apisix --set gateway.type=NodePort --set gateway.k8s_domain="custom.cluster.domain" --set allow.ipList="{10.42.0.0/16}" 
```

The error of apisix-etcd-0 pod is as follows:
```
failed to resolve http://apisix-etcd-0.apisix-etcd-headless.ingress-apisix.svc.cluster.local:2380 to match --initial-cluster=apisix-etcd-0=http://apisix-etcd-0.apisix-etcd-headless.ingress-apisix.svc.cluster.local:2380 (failed to resolve "http://apisix-etcd-0.apisix-etcd-headless.ingress-apisix.svc.cluster.local:2380" (lookup apisix-etcd-0.apisix-etcd-headless.ingress-apisix.svc.cluster.local on 10.43.0.10:53: no such host))
```

**Comment by ncepuwanghui** [comment]
I found the cause of the above problem.
The reason is that the cluster domain name of apisix which set by "--set gateway.k8s_domain", is inconsistent with the domain of etcd chart which is dependent on `apisix-helm-chart`.

[`clusterDomain` in values.yaml of etcd chart](https://github.com/bitnami/charts/blob/master/bitnami/etcd/values.yaml#L188) 
[`gateway.k8s_domain` in values.yaml of apisix-helm-chart](https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/values.yaml#L45)

The cluster domain of etcd chart can be specified by `--set etcd.clusterDomain="your-custom-cluster-domain"`, when installing apisix-helm-chart. As follows:
```
helm install apisix ./charts/apisix --namespace ingress-apisix --set gateway.type=NodePort --set gateway.k8s_domain="custom.cluster.domain" --set etcd.clusterDomain="your-custom-cluster-domain" --set allow.ipList="{10.42.0.0/16}" 
```

**Comment by tokers** [comment]
@ncepuwanghui Yep, the etcd has its own configuration section.
