### ISSUE TITLE
pod pending

### ISSUE THREAD

**Issue by loda13** [apache/apisix-helm-chart#346]
![image](https://user-images.githubusercontent.com/10447318/190293869-67ba7ee5-9008-45e5-8368-95993c484bee.png)

`kubectl describe pods -n apisix apisix-etcd-0`
`Warning  FailedScheduling  4m36s  default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.`

`kubectl describe pods -n apisix apisix-656ff547f4-s7tdt`
`Started container wait-etcd`

**Comment by tokers** [comment]
See https://github.com/apache/apisix-helm-chart/issues/11.
