### ISSUE TITLE
wrong default value in apisix chart readme

### ISSUE THREAD

**Issue by 117503445** [apache/apisix-helm-chart#367]
in <https://github.com/apache/apisix-helm-chart/tree/master/charts/apisix/README.md>, the default value of `admin.allow.ipList` is `true`. In fact, the default value of `admin.allow.ipList` is `["127.0.0.1/24"]`.

**Comment by tao12345666333** [comment]
thanks, PR's welcome

**Comment by 117503445** [comment]
This is PR <https://github.com/apache/apisix-helm-chart/pull/368>.
