### ISSUE TITLE
doc: need guidelines to deploy apisix without clone this repo

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-helm-chart#37]
For example, `wget` raw files to do certain helm commands, so it would be easier to build apisix.

BTW, after this step, we could add it to installations steps in apisix README

**Comment by BLasan** [comment]
@Yiyiyimu Hi, can't we publish the helm chart into to [artifacthub](https://artifacthub.io/) and install it via the helm command

**Comment by tokers** [comment]
> @Yiyiyimu Hi, can't we publish the helm chart into to [artifacthub](https://artifacthub.io/) and install it via the helm command ?

We already published them to artifacthub, see https://artifacthub.io/packages/search?page=1&ts_query_web=apisix.

**Comment by Yiyiyimu** [comment]
> @Yiyiyimu Hi, can't we publish the helm chart into to [artifacthub](https://artifacthub.io/) and install it via the helm command?

Hi @BLasan Yes but we still need to clone this repo first, then do helm install, which is kind of annoying, to me.

**Comment by Yiyiyimu** [comment]
Fixed by #91
