### ISSUE TITLE
Is chart for version 3 being developed?

### ISSUE THREAD

**Issue by shenzhuangzhi1** [apache/apisix-helm-chart#387]
### Description

I cant find repo of chart package,where is it?

**Comment by tzssangglass** [comment]
> I cant find repo of chart package,where is it?

The helm chart will be updated after the 3.0 LTS release, but is in fact already compatible with V3, see: #357

**Comment by shenzhuangzhi1** [comment]
> > I cant find repo of chart package,where is it?
> 
> The helm chart will be updated after the 3.0 LTS release, but is in fact already compatible with V3, see: #357

Got it, thx
