### ISSUE TITLE
Not available

### ISSUE THREAD

**Issue by freemankevin** [apache/apisix-helm-chart#408]
### Current State

![image](https://user-images.githubusercontent.com/71524776/205805360-77a41b84-a0f7-427a-ba25-9c1ac6585482.png)

![image](https://user-images.githubusercontent.com/71524776/205805417-b754d691-84ff-42d1-89b9-893d88cb758f.png)

### Desired State

available

**Comment by tzssangglass** [comment]
cc @tao12345666333

**Comment by tao12345666333** [comment]
You should check your network performance. We host our Helm chart on GitHub.

Or you can clone the repo to your local

**Comment by freemankevin** [comment]
Solved, but can you directly update the link provided when the helm installation error is reported to github's helm repo?

**Comment by freemankevin** [comment]
It's okay, I read wrong。

**Comment by freemankevin** [comment]
Thanks.

**Comment by tokers** [comment]
@freemankevin Could we close it if this issue was resolved?

**Comment by tao12345666333** [comment]
I will close this one, seems it has been resolved
