### ISSUE TITLE
helm chart 安装apisix和etcd  etcd启动报错

### ISSUE THREAD

**Issue by lichunke** [apache/apisix-helm-chart#410]
环境：阿里云ACK集群
Server Version: v1.22.3-aliyun.1 

NAME  	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART        	APP VERSION
apisix	default  	1       	2022-12-08 18:09:39.316520181 +0800 CST	deployed	apisix-0.11.3	2.15.1 

etcd存储使用阿里云SSD云盘

报错日志：
etcd 06:16:55.19 
etcd 06:16:55.19 Welcome to the Bitnami etcd container
etcd 06:16:55.19 Subscribe to project updates by watching https://github.com/bitnami/containers
etcd 06:16:55.20 Submit issues and feature requests at https://github.com/bitnami/containers/issues
etcd 06:16:55.20 
etcd 06:16:55.20 INFO  ==> ** Starting etcd setup **
etcd 06:16:55.22 INFO  ==> Validating settings in ETCD_* env vars..
etcd 06:16:55.22 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
etcd 06:16:55.22 INFO  ==> Initializing etcd
etcd 06:16:55.22 INFO  ==> Generating etcd config file using env variables
etcd 06:16:55.24 INFO  ==> There is no data from previous deployments
etcd 06:16:55.24 INFO  ==> Bootstrapping a new cluster
etcd 06:17:55.32 ERROR ==> Headless service domain does not have an IP per initial member in the cluster

**Comment by tao12345666333** [comment]
What's your install command?

**Comment by lichunke** [comment]
install command 
helm install apisix apisix/apisix \
  --set apisix.image.tag=3.0.0-debian \
  --set gateway.type=NodePort \
  --set ingress-controller.enabled=true \
  --set etcd.persistence.storageClass="alicloud-disk-ssd" \
  --set etcd.persistence.size="20Gi" \
  --namespace default \
  --set ingress-controller.config.apisix.serviceNamespace=default

**Comment by lichunke** [comment]
cluster local domain is not local   

 need modifiy etcd's values.yaml  
apisix/charts/etcd/values.yaml
![image](https://user-images.githubusercontent.com/10200984/206717402-21c35b37-8090-41a2-852d-493ee2fb3a1e.png)
clusterDomain: cluster.ops
