### ISSUE TITLE
DISCUSS: Split out the Helm charts for APISIX v2 and v3 separately.

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-helm-chart#419]
Currently APISIX v2 and v3 have many differences and are not compatible.

Before releasing the Helm chart used by APISIX v3, we added some compatibility logic to it. However, there are many limitations in this part of the compatible code, which will affect the user's use.

I recommend maintaining v2 and v3 with different versions of the Helm chart.

ref:
* https://github.com/apache/apisix-helm-chart/issues/393
* https://the-asf.slack.com/archives/CUC5MN17A/p1671466576335099
* https://github.com/apache/apisix-helm-chart/issues/406
* https://github.com/apache/apisix-helm-chart/issues/389

**Comment by AlinsRan** [comment]
+1

**Comment by lingsamuel** [comment]
SGTM

**Comment by spacewander** [comment]
LGTM

**Comment by tao12345666333** [comment]
All things have been done. I will close this one. Thanks
