### ISSUE TITLE
CI: Split the helm-docs task so it only needs to be executed once

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-helm-chart#438]
The current helm-docs task will be executed in each matrix,
It's pointless. 

https://github.com/apache/apisix-helm-chart/blob/3a9c4a6bdae6b38efea85f701dcab00324916344/.github/workflows/ci.yaml#L77-L86

We can advance this task so that it is executed only once, which reduces CI time.

**Comment by Pavan-Nambi** [comment]
hey can i work on this?

**Comment by tao12345666333** [comment]
@Pavan-Nambi If you are interested in implementing it, I can assign this issue to you.

Specifically, you only need to move the helm-docs task from the matrix part to the very beginning of the file

ref: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

**Comment by tao12345666333** [comment]
Don't worry. 😃
Thanks for your contributions

**Comment by leowmjw** [comment]
@tao12345666333 Should close issue since PR merged?

**Comment by tao12345666333** [comment]
yes.
