### ISSUE TITLE
After update the apisix-admin to NodePort, still can't visit it on local

### ISSUE THREAD

**Issue by riskgod** [apache/apisix-helm-chart#44]
Hey, I'm try to curl the apisix's api to define the router and the upsteams, but it failed(403 Forbidden) to call the local apisix's api, after research, is the allow_admin not setting in apisix's value.yaml?

**Comment by tokers** [comment]
@riskgod Please give your step to help us reproduce your problem.

**Comment by riskgod** [comment]
https://github.com/apache/apisix-helm-chart/pull/45
Add pr support here.
