### ISSUE TITLE
How to install helm chart in decouple mode?

### ISSUE THREAD

**Issue by naveenkumarer** [apache/apisix-helm-chart#440]
How to install helm chart in decouple mode?

I can see that on chart version basis role traditional is set

{{- $isBeta := (semverCompare ">=2.99.0-0" .Values.apisix.image.tag) }}

    {{- if $isBeta }}
    deployment:
      role: traditional
      role_traditional:
        config_provider: etcd

How to install helm chart in decouple mode?

**Comment by tao12345666333** [comment]
Hi, I submitted one proposal  #459 and PR #461 for this

**Comment by naveenkumarer** [comment]
Thanks @tao12345666333 . I have built something similar locally. Your PR looks good to me. Thanks for that.
