### ISSUE TITLE
feat: allow exposing admin api via ingress resource

### ISSUE THREAD

**Issue by ikatlinsky** [apache/apisix-helm-chart#441]
It can be useful for some environments to expose Apisix admin API publicly via ingress resources. Currently, only gateway itself can be exposed, which seems a bit limiting.

**Comment by tao12345666333** [comment]
As simple as this is, I'd like to know your use case.

this is a very dangerous behavior

Why you want to expose admin API outside  cluster?

**Comment by ikatlinsky** [comment]
we are deploying apisix in the private network, which is not available for public usage and needs a convenient way to interact with admin API for automation purposes. We will need to use port-forward functionality which is definitely not the very production-ready solution.

**Comment by tao12345666333** [comment]
ok, #442 has been merged, I will close this one, thanks
