### ISSUE TITLE
DISCUSS: remove 0.12.x release and release new 0.13.x 

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-helm-chart#448]
APISIX v3 is used in 0.12.x, and some compatible configurations are included in it. But the compatibility logic is not flexible enough, which leads to some problems.

* #393 
* https://the-asf.slack.com/archives/CUC5MN17A/p1671466576335099

In #419, I have split APISIX v2 and v3 into separate versions for maintenance.
Subsequent v0.x versions will be used for APISIX v2. 
And v1.x is used for APISIX v3.

And, we can update APISIX Ingress and APISIX Dashboard versions normally in these Charts.

**Comment by AlinsRan** [comment]
+1
Some 0.12.x release default behaviors are not available

**Comment by gxthrj** [comment]
+1 
It will reduce maintenance costs.
