### ISSUE TITLE
[request help]: 404 not found

### ISSUE THREAD

**Issue by riskgod** [apache/apisix-helm-chart#46]
hey, I have run this in my local k8s, and use online debuger to  test 14.215.177.39 this ip in apisix dashboard, that's works! But,  I defined one route named "/index", and linked to the above ip's upstream, That's failed, it tell me 404 not found.
here is my local svc:
![image](https://user-images.githubusercontent.com/3436287/112463384-1f555500-8d9d-11eb-89b7-20728ecaaa24.png)

<img width="954" alt="Screen Shot 2021-03-25 at 19 04 38" src="https://user-images.githubusercontent.com/3436287/112463235-f634c480-8d9c-11eb-80ae-9c919ae1cfef.png">
<img width="839" alt="Screen Shot 2021-03-25 at 19 06 19" src="https://user-images.githubusercontent.com/3436287/112463424-3136f800-8d9d-11eb-8e98-9e4f88f3638b.png">

**Comment by riskgod** [comment]
Is this problem? 
<img width="472" alt="Screen Shot 2021-03-25 at 20 12 37" src="https://user-images.githubusercontent.com/3436287/112471111-74e22f80-8da6-11eb-8543-5190a70a3088.png">

**Comment by riskgod** [comment]
<img width="886" alt="Screen Shot 2021-03-25 at 20 32 54" src="https://user-images.githubusercontent.com/3436287/112473399-49ad0f80-8da9-11eb-85b8-0e5f369e5ebf.png">

**Comment by riskgod** [comment]
<img width="448" alt="Screen Shot 2021-03-25 at 21 06 25" src="https://user-images.githubusercontent.com/3436287/112477428-f7bab880-8dad-11eb-88ff-e7aafe534f56.png">
This still not work

**Comment by tokers** [comment]
@riskgod As per your diagrams, 30957 is the node port for apisix admin, not the gateway, try 30103 instead.

**Comment by riskgod** [comment]
get it thank you
