### ISSUE TITLE
hpa version will deprecate

### ISSUE THREAD

**Issue by jiangfucheng** [apache/apisix-helm-chart#463]
Hi, hpa version of apisix, apisix-dashboard and ingress-controller is v2bate1, this version is deprecated in new k8s version. So that i want upgrade hpa version from v2bate1 to v2. Please assign to me if think ok.

**Comment by tokers** [comment]
> Hi, hpa version of apisix, apisix-dashboard and ingress-controller is v2bate1, this version is deprecated in new k8s version. So that i want upgrade hpa version from v2bate1 to v2. Please assign to me if think ok.

We consider being compatible with the latest few K8s release (maybe the latest four or five). As long as the `v2` version si available among all of these releases, I think upgrade is OK.

**Comment by tao12345666333** [comment]
Assigned.

I think you can add a configuration item,
Allow users to configure the API version that can be used.
