### ISSUE TITLE
Is there a plan to support the 2.15 version of helm Chart add decoupled mode

### ISSUE THREAD

**Issue by jinjianming** [apache/apisix-helm-chart#466]
At present, I see that 2.15 is a long-term maintenance version and supports DP and CP are deployed independently I hope that a Chart can support APISIX 2.15 decoupled;

https://github.com/apache/apisix-helm-chart/pull/461
https://apisix.apache.org/zh/docs/apisix/2.15/architecture-design/deployment-role/

**Comment by tokers** [comment]
@jinjianming The decoupled mode is a feature introduced since APISIX 3.0.

**Comment by jinjianming** [comment]
Through V2.15 的 docs, I can see decoupling support;

The following address:
https://apisix.apache.org/zh/docs/apisix/2.15/architecture-design/deployment-role/

And this docs does not indicate that 3.0 is required

**Comment by tao12345666333** [comment]
This is an error in the documentation.  decoupled mode is only available in 3.x
