### ISSUE TITLE
Some questions about extPlugins

### ISSUE THREAD

**Issue by SakaZhang** [apache/apisix-helm-chart#489]
1. what's different between extPlugins & customPlugins in values.yaml? It looks like lua scripts in customPlugins?
2. If i have a extPlugin like this:
```
extPlugin:
  enabled: true
  cmd: ["/usr/local/apisix/go-runner/goose", "run"]
```
  how can i put this binary `goose` into apisix Pod?

**Comment by tokers** [comment]
@SakaZhang You need to build your image.

**Comment by SakaZhang** [comment]
> @SakaZhang You need to build your image.

get it.
