### ISSUE TITLE
Request help: need to add dependence chart, such as  etcd 

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix-helm-chart#5]
Since the release of Apache APISIX version 2.0, etcd has been adjusted from v2 to v3. 
We need to explicitly indicate dependencies in the chart to prevent users from reporting errors during the upgrade process.

**Comment by tokers** [comment]
Could helm specifies the minimal version of a dependency?

**Comment by gxthrj** [comment]
We can specify a specific version for dependent charts, but as far as I know the minimum version is not easy to set.

**Comment by tao12345666333** [comment]
In fact we have already set the dependencies. I will close this one. thanks
