### ISSUE TITLE
body-transformer plugin configuration is missing

### ISSUE THREAD

**Issue by yujinchoi-94** [apache/apisix-helm-chart#515]
It seems `body-transformer` plugin configuration is missing in [here](https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/values.yaml#L340-L387).
Do you mind if i submit a PR to fix this?

**Comment by Gallardot** [comment]
@yujinchoi-94  Please feel free to submit a PR at any time. Thank you for your contribution!

**Comment by tao12345666333** [comment]
#518 has been merged. I will close this one, thanks
