### ISSUE TITLE
feat: Customize the readiness probe of APISIX pod

### ISSUE THREAD

**Issue by joyyir** [apache/apisix-helm-chart#545]
The current version of APISIX helm chart cannot change the readiness probe of APISIX pod. ([Source Code](https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/templates/_pod.tpl#L108))
It would be nice to support customizing the readiness probe of APISIX pod. It is probably needed to change the readiness probe, especially when using external plugins. Currently, the 10 second delay is not sufficient to prepare external plugins.

**Comment by Gallardot** [comment]
Agree. Welcome to submit a PR to make it possible!

**Comment by lingsamuel** [comment]
Closing since the PR merged
