### ISSUE TITLE
用helm install apisix-gw ./apisix命令安装后，dashboard访问etcd失败

### ISSUE THREAD

**Issue by zhangwenjian** [apache/apisix-helm-chart#55]
When custom name used in helm install command is not same with the service name defined in values.yaml, the dashboard will fail to access etcd service.

Labels below must be vairables:

[root@master01 ~]# grep apisix-admin ./apisix -R
./apisix/templates/service-admin.yaml:  - name: apisix-admin
./apisix/charts/apisix-ingress-controller/values.yaml:    baseURL: "http://apisix-admin:9180/apisix/admin"

[root@master01 ~]# grep apisix-etcd ./apisix -R
./apisix/charts/apisix-dashboard/values.yaml:        - apisix-etcd:2379

**Comment by tokers** [comment]
You should also pass the custom apisix admin service fullname when you installing apisix-ingress-controller by:

```shell
helm install apisix-ingress-controller apisix/apisix-ingress-controller --set config.apisix.baseURL=http://{name of apisix admin}:{port}
```

By the way, we'd better to use English in public channel.

**Comment by wjkhappy14** [comment]
helm install apisix-ingress-controller apisix/apisix-ingress-controller --set config.apisix.baseURL=http://apisix-admin:9180

**Comment by tao12345666333** [comment]
Please try not to reply in an outdated issue, if you encounter a similar problem please add a detailed description. Thanks!

Also, this issue has not been updated for too long, I will close it, if you still have this problem, please feel free to reopen it, or create a new issue.
