### ISSUE TITLE
Duplicate titles  appear in the website

### ISSUE THREAD

**Issue by KishaniKandasamy** [apache/apisix-helm-chart#56]
![Screenshot (107)](https://user-images.githubusercontent.com/53715187/114130199-acf87f00-991d-11eb-9f78-ad555b4a0cae.png)

**Comment by KishaniKandasamy** [comment]
Hi , even the commit was merged it  still shows the same(like Duplicate titles ) as before🤔
@juzhiyuan  @tokers  @membphis 

![Screenshot (113)](https://user-images.githubusercontent.com/53715187/114502554-94ec6c80-9c49-11eb-8bbf-4570c4b34661.png)

**Comment by juzhiyuan** [comment]
Hi, does this title removed from original markdown file content?

**Comment by KishaniKandasamy** [comment]
> Hi, does this title removed from original markdown file content?

#57

**Comment by juzhiyuan** [comment]
ok, let me reopen & check

**Comment by KishaniKandasamy** [comment]
> ok, let me reopen & check

yes 👍🏻

**Comment by juzhiyuan** [comment]
https://apisix.apache.org/docs/helm-chart/apisix-ingress-controller
