### ISSUE TITLE
API-key not taken into account in apisix-2.0.0

### ISSUE THREAD

**Issue by cg-scorpio** [apache/apisix-helm-chart#567]
With apisix-2.0.0 the api keys provided in the values.yaml file are no longer taken into account. The default key is used systematically. I tried using the API keys directly in the admin.credentials.admin and admin.credentials.viewer fields, but also using a secret. In both cases, the API key accepted by API-SIX is the default key.
En revanche, avec APISIX-3.1, cela fonctionne

**Comment by tao12345666333** [comment]
@lingsamuel PTAL, thanks

**Comment by moonming** [comment]
@sn0rt

**Comment by Sn0rt** [comment]
pls assign to me

**Comment by lingsamuel** [comment]
What's your config? I have checked it and it works fine.

Here is my deploy command:
```bash
❯ helm install apisix ~/apisix-helm-chart/charts/apisix --create-namespace \
  --set gateway.type=NodePort \
  --namespace ingress-apisix \
  --set apisix.admin.credentials.admin="abcde"
```

And it works well:
![image](https://github.com/apache/apisix-helm-chart/assets/14567045/01172fb6-99ce-44d4-b681-5bf78fed2d92)

**Comment by lingsamuel** [comment]
`2.0.0` is under dev branch and `admin.credentials.admin` has been moved to `apisix.admin.credentials.admin`
