### ISSUE TITLE
help: why do we need an init container with privileged context

### ISSUE THREAD

**Issue by ikatlinsky** [apache/apisix-helm-chart#584]
In PR https://github.com/apache/apisix-helm-chart/commit/e1e02feb8546eb94b26127a6046ef357d9aba909 we added an init container that requires privileged execution context. Based on Kubernetes pod security standards (https://kubernetes.io/docs/concepts/security/pod-security-standards/) it is not allowed for baseline and upper levels of security. That means that apisix will not be deployable to any cluster which has reasonable security defaults.

Of course, I can override this init container, but guess it was added for some reason.

Questions are:
1. why do we need to modify system configurations?
2. if we still need that - can it be moved to the image creation phase?

Thanks, @tao12345666333 hope you will be able to help

**Comment by ikatlinsky** [comment]
Ok, got it. Are there any proposals on how to deal with cases when privileged pods are not allowed by cluster settings?

**Comment by tao12345666333** [comment]
If the cluster does not allow privileged pods to exist, there are two ways to handle it:

1. Set it as empty and skip it.
2. Modify the cluster policy to allow it.

In fact, it is just a recommended configuration. In most cases, it can still work normally without this configuration. You can modify it after encountering problems (such as high traffic scenarios).
