### ISSUE TITLE
Charts and artifactsHub/Documentation are not consistent

### ISSUE THREAD

**Issue by ventaubain** [apache/apisix-helm-chart#610]
Hi,

There are some differences between the Helm chart and the helm in artifactHub (repo https://charts.apiseven.com). 

These differences breaks some tutorial as https://apisix.apache.org/docs/ingress-controller/tutorials/manage-ingress-certificates-with-cert-manager and https://apisix.apache.org/docs/ingress-controller/tutorials/manage-certificates-with-cert-manager/ for example (due to the gateway -> service/ssl names updates)

This one can't work for example:
`helm install apisix apisix/apisix --set **gateway.type=NodePort** --set ingress-controller.enabled=true --set **gateway.tls.enabled=true** --set ingress-controller.config.apisix.serviceNamespace=default`

It is not friendly for new users or for debugging. It should be nice to clean all the differences.

Thanks

**Comment by tao12345666333** [comment]
thank you for your feedback. This is due to the fact that we released the v2.x version of the Helm chart on the dev branch, which contains many breaking changes. And since it has a higher version number, it will always be displayed by default. 

But other documents still use v1.x version

**Comment by ventaubain** [comment]
Thanks for your response ! 
The doc update will be released soon ?
