### ISSUE TITLE
Question: appVersion: 3.7.0 for the Apisix Helm Chart

### ISSUE THREAD

**Issue by ruanbekker** [apache/apisix-helm-chart#668]
Hi everyone,

Any ideas when the application version will be bumped to 3.7.0? 

I noticed the downloads page shows [3.7.0 as current](https://apisix.apache.org/downloads/), and links to [Dockerhub](https://hub.docker.com/r/apache/apisix/tags) but the latest image.tag is `3.6.0-debian`.

I had a look at the latest tag on the helm chart repo [2.3.1](https://github.com/apache/apisix-helm-chart/blob/apisix-2.3.1/charts/apisix/Chart.yaml) which is on 3.6.0 application version.

**Comment by AlinsRan** [comment]
The help chart repo [2.4.0](https://github.com/apache/apisix-helm-chart/releases/tag/apisix-2.4.0) has been released.
This package defaults to using the apisix:3.7.0-debian image.
