### ISSUE TITLE
helm 安装apisix 启动tls 安装报错

### ISSUE THREAD

**Issue by kingGang** [apache/apisix-helm-chart#67]
- env
  - azure k8s 1.18.14
  - apisix 2.4-alpine
  - dashboard 2.5
  - etcd 默认网上拉取的
  - controller 0.5.0
- 修改配置
   apisix-helm-chart/charts/apisix/values.yaml
     22行：image.tag:2.4-alpine
     53行： gateway.tls.enabled: true
     60行： gateway.ingress.enabled: true
- 执行过程
   1、helm dependency update charts/apisix/
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://charts.bitnami.com/bitnami" chart repository
Saving 3 charts
Downloading etcd from repo https://charts.bitnami.com/bitnami
   2、helm install apisix charts/apisix   --set gateway.type=LoadBalancer   --set allow.ipList="{0.0.0.0/0}"   --namespace ingress-apisix
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http): missing required field "paths" in io.k8s.api.networking.v1beta1.HTTPIngressRuleValue

**Comment by tokers** [comment]
> 60行： gateway.ingress.eabled: true
Is this a typo?

@kingGang You need to provide at least one host + path configuration for Ingress, currently, there is no default pair for that.

**Comment by tokers** [comment]
> > 60行： gateway.ingress.eabled: true
> > Is this a typo?
> 
> @kingGang You need to provide at least one host + path configuration for Ingress, currently, there is no default pair for that.

Such as: --set 'gateway.ingress.hosts[0].host=apisix.local' --set 'gateway.ingress.hosts[0].paths={/*}'.

**Comment by kingGang** [comment]
> > 60行： gateway.ingress.eabled: true
> > Is this a typo?
> 
> @kingGang You need to provide at least one host + path configuration for Ingress, currently, there is no default pair for that.

不好意思，是写错了，已经改过来了！
我是希望通过crd的方式去配置host和path

**Comment by kingGang** [comment]
> > > 60行： gateway.ingress.eabled: true
> > > Is this a typo?
> > 
> > 
> > @kingGang You need to provide at least one host + path configuration for Ingress, currently, there is no default pair for that.
> 
> Such as: --set 'gateway.ingress.hosts[0].host=apisix.local' --set 'gateway.ingress.hosts[0].paths={/*}'.

非常感谢，按照你的方法我已经成功了！

**Comment by tokers** [comment]
You're welcome.
