### ISSUE TITLE
proposal: restructure the apisix-helm-chart repo

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix-helm-chart#70]
Currently we provide three available charts:

* apisix
* apisix-dashboard
* apisix-ingress-controller

But both apisix-dashboard and apisix-ingress depend on apisix to work properly (and apisix is the core).

Now in our documents, for example, [in the installation steps of apisix-ingress](http://apisix.apache.org/docs/ingress-controller/deployments/ack), apisix needs to be deployed first, and then apisix-ingress needs to be deployed, which causes a certain amount of trouble for users.

With reference to many other open source projects, I suggest to adjust the Chart structure.

The goal is: users can use one helm command to complete the deployment (for example, one command to deploy apisix and apisix-ingress, apisix-dashboard is optional)

**Comment by tao12345666333** [comment]
cc @tokers @gxthrj

**Comment by tokers** [comment]
That's cool, +1

By the way, currently, apisix-ingress-controller and apisix-dashboard were set as dependencies of apisix, but the repositories are wrong, which results in apisix-ingress-controller and apisix-dashboard will be installed unconditionly.

**Comment by tokers** [comment]
We may also support upgrading one of the components.

**Comment by tao12345666333** [comment]
> By the way, currently, apisix-ingress-controller and apisix-dashboard were set as dependencies of apisix, but the repositories are wrong, which results in apisix-ingress-controller and apisix-dashboard will be installed unconditionly.

let me fix it.

**Comment by tao12345666333** [comment]
> We may also support upgrading one of the components without upgrading/installing others.

sure.

**Comment by gxthrj** [comment]
Do we only need to provide one APISIX charts? `Ingress` and `dashboard` use different templates to manage  in this charts.

**Comment by tao12345666333** [comment]
@gxthrj We can only provide one APISIX chart, but I want to retain the three (all of our projects can **only using APISIX chart in docs/guides**)

The reason for retaining the other two is that we support the deployment of APISIX in non-k8s environments, or pre-deployment of APISIX. (of course, this can also be done by providing a switch in the chart of APISIX)

**Comment by tao12345666333** [comment]
please assign to me

**Comment by tao12345666333** [comment]
I think we've reached this goal
