### ISSUE TITLE
Apisix Gateway Ingress ```externalTrafficPolicy``` missing setting

### ISSUE THREAD

**Issue by BenB196** [apache/apisix-helm-chart#88]
Currently, you are unable to change ```externalTrafficPolicy``` via the apisix helm chart for the [service gateway template](https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/templates/service-gateway.yaml).

This is useful if you want to change from ```Cluster``` to ```Local```

**Comment by tao12345666333** [comment]
thanks！

/assign
